var a= 10;
console.log(a);
a= true;
console.log(a);     
a= "hello";
console.log(a); 
a= null;
console.log(a); 
a= undefined;   
console.log(a);
a= {name: "John", age: 30};
console.log(a); 
a= [1, 2, 3, 4, 5];
console.log(a);
a= function() { return "Hello"; };
console.log(a); 
console.log(a()); 
a= Symbol("id");
console.log(a); 
a= BigInt(123456789012345678901234567890);
console.log(a); 
a= NaN;
console.log(a);
a= Infinity;
console.log(a); 
a= -Infinity;
console.log(a);
a= new Date();
console.log(a); 
a= /abc/;
console.log(a);
a= new Map();
console.log(a); 
a= new Set();
console.log(a); 
a= new WeakMap();
console.log(a); 
a= new WeakSet();
console.log(a); 
a= new Error("Something went wrong");   
console.log(a); 
a= new Array(1, 2, 3);
console.log(a); 
a= new Object();
console.log(a); 
a= new Boolean(true); 